### ISSUE TITLE
Documentation unclear / outdated?

### ISSUE THREAD

**Issue by khink** [springload/wagtailenforcer#4]
The README says to put `wagtailadmin_urls.urlpatterns = wagtailenforcer_urls + wagtailadmin_urls.urlpatterns` at the top of `urls.py`, but doesn't say from where to import `wagtailenforcer_urls`. A search  in the repo yields no results.

Also on startup i get `ModuleNotFoundError: No module named 'signals'`, which is not required in `setup.py`, so i suspect that should be updated as well.

Tested this on Django 1.11, Python3.

**Comment by loicteixeira** [comment]
Hi @khink, thanks for the report.

I do not have time to review the documentation at the moment, but you will be able to import `wagtailenforcer_urls` as follow `from wagtailenforcer import urls as wagtailenforcer_urls`.

Regarding the import error, I'm due to update a website to Django 1.11 so I'll probably bump into the same issue and will look  at fixing it then.

**Comment by loicteixeira** [comment]
e91975c5d31e19848998a94bdb33e92a95900c56 updates the documentation and #5 adds compatibility with Django 1.10 and 1.11 but we still need to investigate #8. Despite this remaining issue, I'll release a new version shortly which should get rid of all the errors for now.
